// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSyKuBkkWfhClXNT5pq9SqRjXINiVIVTg',
    appId: '1:656387851866:web:97a1c4c88fb4318585fa63',
    messagingSenderId: '656387851866',
    projectId: 'portfolio-7474e',
    authDomain: 'portfolio-7474e.firebaseapp.com',
    storageBucket: 'portfolio-7474e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU4sbx2kf9znZiz_Vub2x0QjpP5Kq8oL0',
    appId: '1:656387851866:android:e384c78a973ef4f185fa63',
    messagingSenderId: '656387851866',
    projectId: 'portfolio-7474e',
    storageBucket: 'portfolio-7474e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEs0GXt935tKVj6RLrSyo8NMLXMpoaHU',
    appId: '1:656387851866:ios:3d710984a0fac17285fa63',
    messagingSenderId: '656387851866',
    projectId: 'portfolio-7474e',
    storageBucket: 'portfolio-7474e.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADEs0GXt935tKVj6RLrSyo8NMLXMpoaHU',
    appId: '1:656387851866:ios:3d710984a0fac17285fa63',
    messagingSenderId: '656387851866',
    projectId: 'portfolio-7474e',
    storageBucket: 'portfolio-7474e.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSyKuBkkWfhClXNT5pq9SqRjXINiVIVTg',
    appId: '1:656387851866:web:b073a611af90a4ab85fa63',
    messagingSenderId: '656387851866',
    projectId: 'portfolio-7474e',
    authDomain: 'portfolio-7474e.firebaseapp.com',
    storageBucket: 'portfolio-7474e.firebasestorage.app',
  );
}